"""Add initial tables

Revision ID: 13085c3e5feb
Revises:
Create Date: 2022-02-10 17:55:52.909179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13085c3e5feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'driver_meta',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organisation', sa.String(length=64), nullable=False),
        sa.Column('project', sa.String(length=64), nullable=False),
        sa.Column('last_seen_ts', sa.DateTime(), nullable=True),
        sa.Column('last_maintenance_ts', sa.DateTime(), nullable=True),
        sa.Column('driver_data', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organisation', 'project', name='organisation_project_constraint'),
    )
    op.create_table(
        'catalog_entry',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=64), nullable=False),
        sa.Column('platform_uuid', sa.String(length=36), nullable=False),
        sa.Column('data', sa.JSON(), nullable=False),
        sa.Column('driver_meta_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['driver_meta_id'],
            ['driver_meta.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'synthetic_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=64), nullable=False),
        sa.Column('last_seen_ts', sa.DateTime(), nullable=True),
        sa.Column('platform_uuid', sa.String(length=48), nullable=False),
        sa.Column('driver_meta_id', sa.Integer(), nullable=True),
        sa.Column('profile_data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ['driver_meta_id'],
            ['driver_meta.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synthetic_user')
    op.drop_table('catalog_entry')
    op.drop_table('driver_meta')
    # ### end Alembic commands ###
