"""Add active status

Revision ID: 7e3927bbc384
Revises: 13085c3e5feb
Create Date: 2022-05-20 17:50:05.188259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3927bbc384'
down_revision = '13085c3e5feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synthetic_user', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=str(True)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('synthetic_user', 'is_active')
    # ### end Alembic commands ###
