name: PyLint Runner
description: 'Checks python code style'
author: 'doedotdev, Sergio Carracedo <sergio@benshi.ai>'
inputs:
  path:
    description: Code path relative to repository
    required: false
    default: ./src

runs:
  using: composite
  steps:
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install flake8
      shell: bash
    - name: Run flake8
      run: |
        echo "Running: flake8 ${{ inputs.path }}"
        flake8 --extend-ignore=E203,E266,E501,F403,F401,E712,F821 ${{ inputs.path }}
      shell: bash
